### ISSUE TITLE
Help with hover

### ISSUE THREAD

**Issue by AyeshaIkhlas21** [AyeshaIkhlas21/web-design-2-independent-project#6]
<img width="870" alt="Screen Shot 2021-12-13 at 2 34 54 PM" src="https://user-images.githubusercontent.com/77422853/145876532-830c412f-01c1-42a0-8198-17e6055de6e1.png">
<img width="786" alt="Screen Shot 2021-12-13 at 2 35 06 PM" src="https://user-images.githubusercontent.com/77422853/145876536-2a4e38be-5b63-44e0-8be8-a2267b617fae.png">

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
ok can you please provide more information? What are you trying to do, what have you tried, and what isn't working?

**Comment by thatkidmadrid** [comment]
anyways, just based on what you sent...

- you will want to put the hover on the `<a>` not the `<h1>` to have a more correct itneraction, and you would then also be able to give it a focus state 
  - if you want to keep the specificity, you can write something like `h1 a:hover, h1 a:focus { ... }`
- you want to wrap the `<a>` around your name like `<a>Ayesha Ikhlas</a>` because the clickable part of the link has no content in the way you have it in the screenshot

**Comment by AyeshaIkhlas21** [comment]
I added it. It worked but larger screen - it didn't worked. I tried to click it on website.

**Comment by thatkidmadrid** [comment]
ok, you have to include more information for me to be able to help you out. And you need to push your changes so that I can see what you're referring to

**Comment by AyeshaIkhlas21** [comment]
I am sorry. I am confused a little bit. What do you mean?

**Comment by thatkidmadrid** [comment]
you have `z-index: 0` on your h1 that is burying the link behind another component. You will want to change this to 1

**Comment by thatkidmadrid** [comment]
in the small screen the empty image is blocking the h1 link as well, so you can also make sure that the h1 has a `z-index:1`. It's also a good idea to either completely hide the image of fix it's display by removing the 28% width you currently have on it for small screens

![Screen Shot 2021-12-13 at 5 08 44 PM](https://user-images.githubusercontent.com/6340290/145896819-fb7acc26-b9ce-400e-a023-5765f38becc3.png)

In troubleshooting within the browser, it added the z-index as an inline style in html, but you should do it in your css

**Comment by AyeshaIkhlas21** [comment]
In the medium screen and large screen- nav (project and about) didn't work. So - nav: z-index: 0. 
h1- z-index: 1. Is that very different?

**Comment by thatkidmadrid** [comment]
you have the z-index for the h1 set to 0 in your media queries too

**Comment by thatkidmadrid** [comment]
The solution we came up with together on zoom:

- keep the `display:flex` for the header instead of changing to `display: grid`
- remove the other grid-related properties
- add `flex-direction: row` to get the same layout you were trying to have using a css grid.

![Screen Shot 2021-12-13 at 7 59 54 PM](https://user-images.githubusercontent.com/6340290/145913359-4a62fbde-ff67-4e13-b10e-7979bb7a1fee.png)

**Comment by AyeshaIkhlas21** [comment]
![Screen Shot 2021-12-13 at 8 40 12 PM](https://user-images.githubusercontent.com/77422853/145917059-760b94e7-6994-4b38-bc69-0fd5ab32ce5b.png)


I have a trouble with this. I am confused.

**Comment by AyeshaIkhlas21** [comment]
I don't know. How I do that? like put id="skip" tabindex="0"? or role?

**Comment by thatkidmadrid** [comment]
https://webaim.org/resources/contrastchecker/
The colours you chose for the links compared to the background colour do not have anough colour contrast

![Screen Shot 2021-12-13 at 8 57 51 PM](https://user-images.githubusercontent.com/6340290/145918996-38fd113c-e824-4842-95f3-58a87e37fa4f.png)

You have content outside of your `<main>`. Like the error says, all of your content needs to be inside of a landmark (an element with a role)

look at lines 47-77 of your index.html

![Screen Shot 2021-12-13 at 9 00 39 PM](https://user-images.githubusercontent.com/6340290/145919203-6c2d5646-bb6e-4e28-8c2e-fe0c8e6677ab.png)

**Comment by thatkidmadrid** [comment]
move the sections into main...

**Comment by thatkidmadrid** [comment]
your navigation doesn't have the `id="nav"`

you have a skip-link that's pointing to `#nav` but nothing on your page has that id... it should probably be your main navigation

**Comment by AyeshaIkhlas21** [comment]
<main id="nav" role="main"> or <section id="nav">

**Comment by AyeshaIkhlas21** [comment]
main id="nav" role="main" **_or_**   section id="nav"

**Comment by thatkidmadrid** [comment]
the nav should have the id "nav"; the main should have the id "main"

**Comment by AyeshaIkhlas21** [comment]
Last thing: Skip link target: I tried it. Didn't work
<img width="542" alt="Screen Shot 2021-12-13 at 10 23 48 PM" src="https://user-images.githubusercontent.com/77422853/145928075-24179e6b-3779-4deb-a1c2-8fd5fc829518.png">

**Comment by thatkidmadrid** [comment]
please see my above comment, you're still missing the id on the nav

**Comment by AyeshaIkhlas21** [comment]
Got it.
